# -*- coding: utf-8 -*-
#
# English Language RTD & Sphinx config file
#
# Uses ../conf_common.py for most non-language-specific settings.

# Importing conf_common adds all the non-language-specific
# parts to this conf module
try:
    from conf_common import *  # noqa: F403,F401
except ImportError:
    import os
    import sys
    sys.path.insert(0, os.path.abspath('../'))
    from conf_common import *  # noqa: F403,F401

import datetime

current_year = datetime.datetime.now().year
# -- Project information -----------------------------------------------------

project = u'Espressif Camera SDK using Amazon KVS WebRTC SDK for C'
copyright = u'2023-{}, Espressif Systems (Shanghai) Co., Ltd. All Rights Reserved.'.format(current_year)
author = 'Espressif Systems (Shanghai) Co., Ltd.'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# Logo and favicon
html_logo = '../_static/espressif-logo.svg'
html_favicon = '../_static/favicon.ico'
