var annotated_dup =
[
    [ "__RtcDataChannel", "struct____RtcDataChannel.html", "struct____RtcDataChannel" ],
    [ "ChannelInfo", "structChannelInfo.html", "structChannelInfo" ],
    [ "IceConfigInfo", "structIceConfigInfo.html", "structIceConfigInfo" ],
    [ "KvsRtcConfiguration", "structKvsRtcConfiguration.html", "structKvsRtcConfiguration" ],
    [ "NullableBool", "structNullableBool.html", "structNullableBool" ],
    [ "NullableDouble", "structNullableDouble.html", "structNullableDouble" ],
    [ "NullableFloat", "structNullableFloat.html", "structNullableFloat" ],
    [ "NullableInt16", "structNullableInt16.html", "structNullableInt16" ],
    [ "NullableInt32", "structNullableInt32.html", "structNullableInt32" ],
    [ "NullableInt64", "structNullableInt64.html", "structNullableInt64" ],
    [ "NullableInt8", "structNullableInt8.html", "structNullableInt8" ],
    [ "NullableLongDouble", "structNullableLongDouble.html", "structNullableLongDouble" ],
    [ "NullableUint16", "structNullableUint16.html", "structNullableUint16" ],
    [ "NullableUint32", "structNullableUint32.html", "structNullableUint32" ],
    [ "NullableUint64", "structNullableUint64.html", "structNullableUint64" ],
    [ "NullableUint8", "structNullableUint8.html", "structNullableUint8" ],
    [ "ReceivedSignalingMessage", "structReceivedSignalingMessage.html", "structReceivedSignalingMessage" ],
    [ "RtcCertificate", "structRtcCertificate.html", "structRtcCertificate" ],
    [ "RtcConfiguration", "structRtcConfiguration.html", "structRtcConfiguration" ],
    [ "RtcDataChannelInit", "structRtcDataChannelInit.html", "structRtcDataChannelInit" ],
    [ "RtcIceCandidateInit", "structRtcIceCandidateInit.html", "structRtcIceCandidateInit" ],
    [ "RtcIceServer", "structRtcIceServer.html", "structRtcIceServer" ],
    [ "RtcMediaStreamTrack", "structRtcMediaStreamTrack.html", "structRtcMediaStreamTrack" ],
    [ "RtcPeerConnection", "structRtcPeerConnection.html", "structRtcPeerConnection" ],
    [ "RtcRtpReceiver", "structRtcRtpReceiver.html", "structRtcRtpReceiver" ],
    [ "RtcRtpTransceiver", "structRtcRtpTransceiver.html", "structRtcRtpTransceiver" ],
    [ "RtcRtpTransceiverInit", "structRtcRtpTransceiverInit.html", "structRtcRtpTransceiverInit" ],
    [ "RtcSessionDescriptionInit", "structRtcSessionDescriptionInit.html", "structRtcSessionDescriptionInit" ],
    [ "SignalingChannelDescription", "structSignalingChannelDescription.html", "structSignalingChannelDescription" ],
    [ "SignalingClientCallbacks", "structSignalingClientCallbacks.html", "structSignalingClientCallbacks" ],
    [ "SignalingClientInfo", "structSignalingClientInfo.html", "structSignalingClientInfo" ],
    [ "SignalingMessage", "structSignalingMessage.html", "structSignalingMessage" ]
];