FROM alpine:latest

RUN apk update
RUN apk upgrade
RUN apk add alpine-sdk cmake clang linux-headers perl bash openssl-dev
RUN apk add iptables
RUN apk add ip6tables
ENV CC=gcc
ENV CXX=g++
ENV DEBUG_LOG_SDP=TRUE
ENV AWS_ENABLE_FILE_LOGGING=TRUE

RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip install flask
RUN pip install websocket
RUN apk add --upgrade py3-websocket-client
RUN pip install "websockets==8.1"