---
name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: checkboxes
    id: confirm
    attributes:
      label: Please confirm you have already done the following
      options:
        - label: I have searched the repository for related/existing bug reports
        - label: I have all the details the issue requires
    validations:
      required: true
  - type: checkboxes
    id: prompt
    attributes:
      label: Please answer the following prompt
      options:
        - label: This issue is replicable using the unmodified sample application
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What is the problem? A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What is the expected behavior?
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Behavior
      description: |
        What actually happened?
        
        Please include full errors, uncaught exceptions, stack traces, and relevant VERBOSE logs.
        To get relevant VERBOSE logs from the SDK, you can retrieve by running `export AWS_KVS_LOG_LEVEL=1`

        If you are reporting a memory leak, please provide sufficient evidence such as a `valgrind` output.
        Note that the CI for this repository uses [Google Sanitizers](https://github.com/google/sanitizers)
        to minimize software issues and vulnerabilities.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Provide a self-contained, concise snippet of code that can be used to
        reproduce the issue, or the command used to run the unmodified sample application. Please share
        which SDK you are using as master and as viewer, and also any timing-related information, if
        applicable.
        For more complex issues provide a repo with the smallest sample that reproduces the bug.
        Avoid including business logic or unrelated code, it makes diagnosis more difficult.
    validations:
      required: true
  - type: input
    id: sdk-version
    attributes:
      label: WebRTC C SDK version being used
    validations:
      required: true
  - type: input
    id: sdk-previous-version
    attributes:
      label: If it was working in a previous version, which one?
    validations:
      required: false
  - type: input
    id: compiler-version
    attributes:
      label: Compiler and Version used
      description: gcc --version / Visual Studio / clang --version
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating System and version
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform being used
    validations:
      required: true
