/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: signaling.proto */

#ifndef PROTOBUF_C_signaling_2eproto__INCLUDED
#define PROTOBUF_C_signaling_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Kvs__Signaling__SignalingMessage Kvs__Signaling__SignalingMessage;


/* --- enums --- */


/* --- messages --- */

struct  Kvs__Signaling__SignalingMessage
{
  ProtobufCMessage base;
  uint32_t version;
  uint32_t messagetype;
  char *peerclientid;
  char *correlationid;
  ProtobufCBinaryData payload;
  uint32_t payloadlen;
};
#define KVS__SIGNALING__SIGNALING_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kvs__signaling__signaling_message__descriptor) \
, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, 0 }


/* Kvs__Signaling__SignalingMessage methods */
void   kvs__signaling__signaling_message__init
                     (Kvs__Signaling__SignalingMessage         *message);
size_t kvs__signaling__signaling_message__get_packed_size
                     (const Kvs__Signaling__SignalingMessage   *message);
size_t kvs__signaling__signaling_message__pack
                     (const Kvs__Signaling__SignalingMessage   *message,
                      uint8_t             *out);
size_t kvs__signaling__signaling_message__pack_to_buffer
                     (const Kvs__Signaling__SignalingMessage   *message,
                      ProtobufCBuffer     *buffer);
Kvs__Signaling__SignalingMessage *
       kvs__signaling__signaling_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kvs__signaling__signaling_message__free_unpacked
                     (Kvs__Signaling__SignalingMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Kvs__Signaling__SignalingMessage_Closure)
                 (const Kvs__Signaling__SignalingMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor kvs__signaling__signaling_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_signaling_2eproto__INCLUDED */
