/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: signaling.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "signaling.pb-c.h"
void   kvs__signaling__signaling_message__init
                     (Kvs__Signaling__SignalingMessage         *message)
{
  static const Kvs__Signaling__SignalingMessage init_value = KVS__SIGNALING__SIGNALING_MESSAGE__INIT;
  *message = init_value;
}
size_t kvs__signaling__signaling_message__get_packed_size
                     (const Kvs__Signaling__SignalingMessage *message)
{
  assert(message->base.descriptor == &kvs__signaling__signaling_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kvs__signaling__signaling_message__pack
                     (const Kvs__Signaling__SignalingMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kvs__signaling__signaling_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kvs__signaling__signaling_message__pack_to_buffer
                     (const Kvs__Signaling__SignalingMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kvs__signaling__signaling_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Kvs__Signaling__SignalingMessage *
       kvs__signaling__signaling_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Kvs__Signaling__SignalingMessage *)
     protobuf_c_message_unpack (&kvs__signaling__signaling_message__descriptor,
                                allocator, len, data);
}
void   kvs__signaling__signaling_message__free_unpacked
                     (Kvs__Signaling__SignalingMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kvs__signaling__signaling_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor kvs__signaling__signaling_message__field_descriptors[6] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Kvs__Signaling__SignalingMessage, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "messageType",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Kvs__Signaling__SignalingMessage, messagetype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peerClientId",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kvs__Signaling__SignalingMessage, peerclientid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "correlationId",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Kvs__Signaling__SignalingMessage, correlationid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Kvs__Signaling__SignalingMessage, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payloadLen",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Kvs__Signaling__SignalingMessage, payloadlen),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kvs__signaling__signaling_message__field_indices_by_name[] = {
  3,   /* field[3] = correlationId */
  1,   /* field[1] = messageType */
  4,   /* field[4] = payload */
  5,   /* field[5] = payloadLen */
  2,   /* field[2] = peerClientId */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange kvs__signaling__signaling_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor kvs__signaling__signaling_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "kvs.signaling.SignalingMessage",
  "SignalingMessage",
  "Kvs__Signaling__SignalingMessage",
  "kvs.signaling",
  sizeof(Kvs__Signaling__SignalingMessage),
  6,
  kvs__signaling__signaling_message__field_descriptors,
  kvs__signaling__signaling_message__field_indices_by_name,
  1,  kvs__signaling__signaling_message__number_ranges,
  (ProtobufCMessageInit) kvs__signaling__signaling_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
