name: 'PR description checker'
on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jadrol/pr-description-checker-action@v1.0.0
        id: description-checker
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          template-path: "./.github/PULL_REQUEST_TEMPLATE.md"
          comment-github-token: ${{ secrets.GITHUB_TOKEN }}