name: Check Version Mismatch between PR branch and main.

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Get version from PR
        id: pr_version
        run: |
          PR_VERSION=$(grep -Po 'KinesisVideoWebRTCClient VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
          echo "PR_VERSION=$PR_VERSION" >> "$GITHUB_ENV"
          echo "PR Version: $PR_VERSION"

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Get version from main
        id: master_version
        run: |
          MASTER_VERSION=$(grep -Po 'KinesisVideoWebRTCClient VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
          echo "MASTER_VERSION=$MASTER_VERSION" >> "$GITHUB_ENV"
          echo "Main version: $MASTER_VERSION"

      - name: Compare versions
        run: |
          echo "Comparing PR Version: $PR_VERSION with Main Version: $MASTER_VERSION"
          if [ "$MASTER_VERSION" == "$PR_VERSION" ]; then
            echo "Please update the version in CMakeLists.txt file (project(KinesisVideoWebRTCClient VERSION <ver-string> LANGUAGES C). Any PR getting merged to main requires a version update"
            exit 1
          else
            echo "Version update detected."
          fi
